// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgdbdcmovuypyvlxcqxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZGJkY21vdnV5cHl2bHhjcXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTI1MzIsImV4cCI6MjA3MzY4ODUzMn0.BF0IPXNEbP1Sc4AwqL3RGOMI7K7L_eBkkH1VAFyUdm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});